insert into ADDRESS (ID, PUBLICID, STREETNUM, STREETNAME, CITY) values (1, 1, 11, 'Rue AAA', '75000', 'PARIS');
insert into ADDRESS (ID, PUBLICID, STREETNUM, STREETNAME, CITY) values (2, 2, 22, 'Rue BBB', '75000', 'PARIS');
insert into ADDRESS (ID, PUBLICID, STREETNUM, STREETNAME, CITY) values (3, 3, 33, 'Rue CCC', '75000', 'PARIS');