CREATE TABLE ADDRESS (
  ID INT NOT NULL
, PUBLICID VARCHAR2(5) NOT NULL
, STREETNUM INT
, STREETNAME VARCHAR2(20)
, POSTALCODE INT
, CITY VARCHAR2(20)
, CONSTRAINT ADDRESS_PK PRIMARY KEY (ID) ENABLE
);